apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    # The ClusterSecretStore I'll setup in AWS
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: api-secrets # name my app looks for
    creationPolicy: Owner
  data:
    - secretKey: gemini
      remoteRef:
        key: industrial/gemini-api-key # Name of the secret in AWS Secrets Manager
