// <auto-generated />
using System;
using Industrial.Diagnostics.Worker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Industrial.Diagnostics.Worker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428231306_first")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Industrial.Diagnostics.Worker.Features.Diagnostics.TelemetryReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("EngineTemperature")
                        .HasColumnType("double precision");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAnomaly")
                        .HasColumnType("boolean");

                    b.Property<double>("OilPressure")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TelemetryReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
