using System.Diagnostics.Metrics;
using System.Threading.Channels;

namespace Industrial.Sensor.Emulator.Infrastructure;

/// <summary>
/// The emulator's OpenTelemetry instruments.
/// </summary>
/// <remarks>
/// Instruments are only read at export time, so anything in between has to survive
/// The five tallies are Counters because a running total carries that gap, a Gauge does not
///
/// Depth is a Gauge, since the question is how full the channel is right now
/// An UpDownCounter needs a matching -1 per dequeue, and one miss stays wrong forever
/// </remarks>
public sealed class SensorMetrics : IDisposable
{
    public const string MeterName = "Industrial.Sensor.Emulator";

    private readonly Meter _meter;

    public SensorMetrics(Channel<TelemetryDto> channel)
    {
        _meter = new Meter(MeterName);

        Acquired = _meter.CreateCounter<long>(
            "sensor.telemetry.acquired",
            unit: "{reading}",
            description: "Readings generated by the acquisition loop."
        );

        Dropped = _meter.CreateCounter<long>(
            "sensor.telemetry.dropped",
            unit: "{reading}",
            description: "Readings discarded because the in-memory channel was full. Unrecoverable."
        );

        Sent = _meter.CreateCounter<long>(
            "sensor.telemetry.sent",
            unit: "{reading}",
            description: "Readings the gateway accepted."
        );

        Rejected = _meter.CreateCounter<long>(
            "sensor.telemetry.rejected",
            unit: "{reading}",
            description: "Readings the gateway refused with 429 because its own buffer was full."
        );

        Failed = _meter.CreateCounter<long>(
            "sensor.telemetry.failed",
            unit: "{reading}",
            description: "Sends that never got an answer -- gateway unreachable or circuit open."
        );

        // Otel SDK calls this every 60s to send the buffer size to the collector
        _meter.CreateObservableGauge(
            "sensor.channel.depth",
            () => (long)channel.Reader.Count,
            unit: "{reading}",
            description: "Readings buffered in RAM awaiting transmission to the gateway."
        );
    }

    public Counter<long> Acquired { get; }
    public Counter<long> Dropped { get; }
    public Counter<long> Sent { get; }
    public Counter<long> Rejected { get; }
    public Counter<long> Failed { get; }

    // The metrics registry holds a reference to every live Meter
    // So _meter outlives SensorMetrics and keeps reporting
    // The registry doesn't know when a meter should stop reporting
    // SensorMetrics does (its own lifetime), so it should dispose of it
    public void Dispose() => _meter.Dispose();
}
