using System.Diagnostics.Metrics;
using System.Threading.Channels;

namespace Industrial.Sensor.Emulator.Infrastructure;

/// <summary>
/// The emulator's OpenTelemetry instruments.
/// </summary>
/// <remarks>
/// Instruments are read only at export time. The tallies are counters because a running total
/// still reflects events between exports, while a gauge would lose them.
///
/// Channel depth is an observable gauge because the question is how full the channel is now. An
/// UpDownCounter would need a matching decrement per dequeue, and one missed decrement would stay
/// wrong permanently.
/// </remarks>
public sealed class SensorMetrics : IDisposable
{
    public const string MeterName = "Industrial.Sensor.Emulator";

    private readonly Meter _meter;
    private readonly Histogram<double> _deliveryDuration;

    public SensorMetrics(Channel<TelemetryDto> channel)
    {
        _meter = new Meter(MeterName);

        Acquired = _meter.CreateCounter<long>(
            "sensor.telemetry.acquired",
            unit: "{reading}",
            description: "Readings generated by the acquisition loop."
        );

        Dropped = _meter.CreateCounter<long>(
            "sensor.telemetry.dropped",
            unit: "{reading}",
            description: "Readings discarded because the in-memory channel was full. Unrecoverable."
        );

        Sent = _meter.CreateCounter<long>(
            "sensor.telemetry.sent",
            unit: "{reading}",
            description: "Readings the gateway accepted."
        );

        Rejected = _meter.CreateCounter<long>(
            "sensor.telemetry.rejected",
            unit: "{reading}",
            description: "Readings discarded after the gateway returned anything other than 202."
        );

        Failed = _meter.CreateCounter<long>(
            "sensor.telemetry.failed",
            unit: "{reading}",
            description: "Sends that never got an answer -- gateway unreachable or circuit open."
        );

        DeliveryDropped = _meter.CreateCounter<long>(
            "sensor.telemetry.delivery_dropped",
            unit: "{reading}",
            description: "Dequeued readings intentionally discarded after the bounded delivery policy ended without a 202."
        );

        _deliveryDuration = _meter.CreateHistogram<double>(
            "sensor.telemetry.delivery.duration",
            unit: "ms",
            description: "End-to-end duration of one dequeued reading's bounded HTTP delivery policy."
        );

        // Sampled by the SDK at each export.
        _meter.CreateObservableGauge(
            "sensor.channel.depth",
            () => (long)channel.Reader.Count,
            unit: "{reading}",
            description: "Readings buffered in RAM awaiting transmission to the gateway."
        );
    }

    public Counter<long> Acquired { get; }
    public Counter<long> Dropped { get; }
    public Counter<long> Sent { get; }
    public Counter<long> Rejected { get; }
    public Counter<long> Failed { get; }
    public Counter<long> DeliveryDropped { get; }

    public void RecordDeliveryDuration(double milliseconds, string outcome) =>
        _deliveryDuration.Record(
            milliseconds,
            new KeyValuePair<string, object?>("outcome", outcome)
        );

    // The global meter registry keeps every live Meter reporting, so this owner disposes it.
    public void Dispose() => _meter.Dispose();
}
