using System.Diagnostics;
using Google.Protobuf.WellKnownTypes;
using Grpc.Core;
using Industrial.Ingestion.Api; // generated from Protos/telemetry.proto
using Industrial.Sensor.EdgeGateway.Configuration;
using Industrial.Sensor.EdgeGateway.Features.Buffer;
using Industrial.Sensor.EdgeGateway.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace Industrial.Sensor.EdgeGateway.Features.Upload;

/// <summary>
/// THE SENDER. Drains local SQLite buffer to send readings to the cloud over gRPC.
/// </summary>
/// <remarks>
/// This loop is independent from acquisition (receiver endpoint)
///
/// Delivery is ALO, ambiguous failures re-send, and cloud dedupes via MessageId (EffO)
/// We send oldest-first ID and delete only what AcceptedCount confirms
///
/// Doesn't use gRPC's default retry policy
/// It would re-send everything without knowing what persisted
/// </remarks>
public class UploaderWorker(
    IServiceScopeFactory scopeFactory,
    EdgeMetrics metrics,
    BufferDepth bufferDepth,
    IOptions<UploaderOptions> uploaderOptions,
    ILogger<UploaderWorker> logger
) : BackgroundService
{
    // How many records to move per stream
    // Bigger -> fewer round trips but a lost response re-sends more dedupes to the cloud
    private readonly int _batchSize = uploaderOptions.Value.BatchSize;

    // Poll interval for when the buffer is empty
    // It's usually empty, so it's usually long a fresh reading waits to ship
    private readonly TimeSpan _idleDelay = TimeSpan.FromMilliseconds(
        uploaderOptions.Value.IdleDelayMs
    );

    // Base of the retry wait, doubled per consecutive failure
    // Full jitter: each wait is drawn uniformly from zero up to that bound
    private readonly TimeSpan _baseBackoff = TimeSpan.FromSeconds(
        uploaderOptions.Value.BaseBackoffSeconds
    );

    // Where the doubling stops, so a long outage keeps retrying instead of drifting to hours
    private readonly TimeSpan _maxBackoff = TimeSpan.FromSeconds(
        uploaderOptions.Value.MaxBackoffSeconds
    );

    // Wall clock ceiling on a single stream, so a connection that stops answering cannot park the loop
    private readonly TimeSpan _uploadTimeout = TimeSpan.FromSeconds(
        uploaderOptions.Value.UploadTimeoutSeconds
    );

    // Failures since the last accepted batch, which resets it to 0
    // This one only sizes the wait, so a local fault and a refusal are allowed to lengthen it
    private int _consecutiveFailures;

    // Consecutive unreachable results, which is what decides whether an outage logs loudly or quietly
    // Kept apart from _consecutiveFailures because a refusal or a full disk bumps that one, and either would silence the single line an operator needs to see
    private int _consecutiveUnreachable;

    // Set when the cloud rejects a batch on content, so the next pass sends one record and learns which one it is
    private bool _isolating;

    // Consecutive single readings the cloud called invalid
    // Past the cap, a broken cloud is likelier than that many bad readings in a row, so dropping stops and the buffer is allowed to back up
    private int _consecutivePoisonDrops;

    private const int MaxConsecutivePoisonDrops = 10;

    // Passes left before the depth gauge is rebuilt from a real COUNT(*)
    // Starts at zero so the first pass resyncs, which is what seeds the estimate for a gateway that boots with a full buffer
    private int _passesUntilDepthResync;

    private const int PassesBetweenDepthResyncs = 100;

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        logger.LogInformation(
            "Edge uploader started. Batch size {BatchSize}, idle poll {IdleDelay}.",
            _batchSize,
            _idleDelay
        );

        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                // We're in a BackgroundService (singleton liftime), so we need to scope deps
                using var scope = scopeFactory.CreateScope();
                var db = scope.ServiceProvider.GetRequiredService<EdgeDbContext>();
                // This type is generated by grpc_csharp_plugin using the service definition in .proto
                var grpcClient =
                    scope.ServiceProvider.GetRequiredService<TelemetryIngestion.TelemetryIngestionClient>();

                // This method refreshes the values that the gauges read so Otel gets fresh data
                // This invocation is important during a cloud outage (gives us visibility)
                await RefreshGaugesAsync(db, stoppingToken);

                // SQLite assigns IDs in insert order, a lower ID means an older reading
                var pending = await db
                    .TelemetryRecords.OrderBy(r => r.Id) // oldest -> youngest
                    .Take(_isolating ? 1 : _batchSize) // takes the first N rows
                    .ToListAsync(stoppingToken);

                if (pending.Count == 0)
                {
                    await SafeDelayAsync(_idleDelay, stoppingToken);
                    continue;
                }

                // Draining oldest-first means an unsendable row (poison msg) stalls every new reading
                // I handle this by dropping it and logging it
                var batch = new List<PendingUpload>(pending.Count);
                var poisoned = new List<TelemetryRecord>();

                foreach (var item in pending)
                {
                    try
                    {
                        batch.Add(new PendingUpload(item, ToRequest(item)));
                    }
                    catch (Exception ex)
                    {
                        // Request obj is malformed (nulls, range violation)
                        logger.LogError(
                            ex,
                            "Dropping unsendable reading {MessageId} from {EquipmentId}.",
                            item.MessageId,
                            item.EquipmentId
                        );
                        poisoned.Add(item);
                    }
                }

                // Remove any poisoned msgs
                if (poisoned.Count > 0)
                {
                    db.TelemetryRecords.RemoveRange(poisoned);
                    await db.SaveChangesAsync(stoppingToken);
                    metrics.Poisoned.Add(poisoned.Count);
                    bufferDepth.Decrement(poisoned.Count);
                }

                if (batch.Count == 0)
                    continue;

                var result = await UploadBatchAsync(grpcClient, batch, stoppingToken);

                // No default arm on purpose
                // A fifth outcome should fall through to the delete below and be caught in review
                // rather than compile into a silent case
                switch (result.Outcome)
                {
                    case UploadOutcome.Malformed:
                        await IsolateOrDropAsync(db, batch, stoppingToken);
                        continue;

                    // Both already logged themselves, and neither leaves anything safe to delete
                    case UploadOutcome.Unreachable:
                    case UploadOutcome.Refused:
                        await BackoffAsync(stoppingToken);
                        continue;

                    // The cloud took none of them, so there is nothing to delete and no reason to hammer it
                    case UploadOutcome.Answered when result.Accepted <= 0:
                        await BackoffAsync(stoppingToken);
                        continue;
                }

                // Delete ONLY what the cloud confirmed
                // It will retry failed reqs in the next pass
                // Dying between the ACK and this delete will resend the entire batch (all dupes)
                db.TelemetryRecords.RemoveRange(batch.Take(result.Accepted).Select(p => p.Record));
                await db.SaveChangesAsync(stoppingToken);

                metrics.Uploaded.Add(result.Accepted);
                metrics.SetCloudReachable(true);
                bufferDepth.Decrement(result.Accepted);
                _consecutiveFailures = 0;
                _consecutiveUnreachable = 0;
                _isolating = false;
                _consecutivePoisonDrops = 0;

                if (result.Accepted < batch.Count)
                {
                    logger.LogWarning(
                        "Cloud accepted {Accepted}/{Sent}. Retrying the remainder.",
                        result.Accepted,
                        batch.Count
                    );
                }
            }
            catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested)
            {
                // Normal shutdown, not a cloud outage
                break;
            }
            catch (Exception ex)
            {
                // A bug or a local failure (disk full, corrupt database)
                // But not the cloud, outages are handled in UploadBatchAsync()
                logger.LogError(ex, "Unexpected failure in the uploader loop.");
                await BackoffAsync(stoppingToken);
            }
        }

        logger.LogInformation("Edge uploader stopped.");
    }

    private async Task<UploadResult> UploadBatchAsync(
        TelemetryIngestion.TelemetryIngestionClient grpcClient,
        List<PendingUpload> batch,
        CancellationToken cancellationToken
    )
    {
        // The gateway returns 202 on receipt and breaks the trace
        // This fans them in so the new trace can reference them
        var links = BuildTraceLinks(batch);

        // Activity is .NET's span (predates OTel)
        using var activity = EdgeTracing.Source.StartActivity(
            "edge.upload",
            ActivityKind.Client,
            parentContext: default,
            links: links
        );
        activity?.SetTag("edge.batch.size", batch.Count);
        activity?.SetTag("edge.batch.linked_traces", links.Count);

        try
        {
            // A deadline as well as the token, because the token only trips on shutdown
            // Nothing else bounds a stream the cloud accepted and then stopped answering, and that hangs the loop with no backoff and no log
            using var call = grpcClient.StreamTelemetry(
                deadline: DateTime.UtcNow.Add(_uploadTimeout),
                cancellationToken: cancellationToken
            );

            try
            {
                foreach (var pending in batch)
                {
                    await call.RequestStream.WriteAsync(pending.Request, cancellationToken);
                }

                await call.RequestStream.CompleteAsync();
            }
            catch (InvalidOperationException)
            {
                // The server answered before reading the whole stream, which is exactly what it does on its first Kafka failure
                // Grpc.Net reports a write to an already-finished call this way rather than as an RpcException, and the response still carries the accepted count
            }

            var response = await call.ResponseAsync;

            var accepted = response.Success ? response.AcceptedCount : 0;
            activity?.SetTag("edge.batch.accepted", accepted);
            return new UploadResult(UploadOutcome.Answered, accepted);
        }
        catch (RpcException ex)
            when (ex.StatusCode == StatusCode.Cancelled && cancellationToken.IsCancellationRequested)
        {
            // ThrowOperationCanceledOnCancellation is false by default, so a cancelled call
            // arrives as a status instead of the exception the filter above expects
            throw new OperationCanceledException(cancellationToken);
        }
        catch (RpcException ex)
            when (ex.StatusCode is StatusCode.InvalidArgument or StatusCode.OutOfRange)
        {
            // The cloud answered, so it is reachable and this batch's contents are the problem
            // Retrying it unchanged would stall every newer reading behind it, so the loop narrows the batch instead
            activity?.SetStatus(ActivityStatusCode.Error, ex.Message);
            metrics.UploadFailures.Add(1);
            metrics.SetCloudReachable(true);
            return new UploadResult(UploadOutcome.Malformed, 0);
        }
        catch (RpcException ex)
            when (ex.StatusCode
                is StatusCode.Unauthenticated
                    or StatusCode.PermissionDenied
                    or StatusCode.Unimplemented
            )
        {
            // The cloud is up and refusing this caller, so reshaping the batch cannot help and nothing here is safe to drop
            // Logged every pass instead of going quiet the way an outage does, because only a config change clears it
            activity?.SetStatus(ActivityStatusCode.Error, ex.Message);
            metrics.UploadFailures.Add(1);
            metrics.SetCloudReachable(true);
            logger.LogError(
                ex,
                "Cloud refused the upload with {Status}. Buffering until this is fixed.",
                ex.StatusCode
            );
            return new UploadResult(UploadOutcome.Refused, 0);
        }
        catch (RpcException ex)
        {
            // Covers a failed connection, an expired deadline, and every status not singled out above
            // A local bug is not in here, it belongs to the loop's handler
            activity?.SetStatus(ActivityStatusCode.Error, ex.Message);
            metrics.UploadFailures.Add(1);
            metrics.SetCloudReachable(false);

            // Log the first failure loudly, then quietly
            // A 30 minute outage should not produce 30 minutes of identical ERROR lines
            _consecutiveUnreachable++;

            if (_consecutiveUnreachable == 1)
                logger.LogWarning(ex, "Cloud unreachable. Buffering locally.");
            else
                logger.LogDebug(
                    "Cloud still unreachable ({Attempts} attempts).",
                    _consecutiveUnreachable
                );

            return new UploadResult(UploadOutcome.Unreachable, 0);
        }
    }

    /// <summary>
    /// Handles a batch the cloud answered and refused on content.
    /// </summary>
    /// <remarks>
    /// One record per pass finds the offender, and only that record is dropped
    /// The alternative, dropping the whole batch on the first rejection, throws away 199 readings the cloud never objected to
    ///
    /// Capped, because a cloud that calls everything invalid would otherwise empty the buffer one record per round trip
    /// Past the cap this holds the queue instead, which is the failure an operator can still fix
    /// </remarks>
    private async Task IsolateOrDropAsync(
        EdgeDbContext db,
        List<PendingUpload> batch,
        CancellationToken cancellationToken
    )
    {
        if (batch.Count > 1)
        {
            _isolating = true;
            return;
        }

        if (_consecutivePoisonDrops >= MaxConsecutivePoisonDrops)
        {
            logger.LogError(
                "Cloud rejected {Drops} readings in a row. Holding {MessageId} and everything behind it.",
                _consecutivePoisonDrops,
                batch[0].Record.MessageId
            );
            await BackoffAsync(cancellationToken);
            return;
        }

        logger.LogError(
            "Cloud rejected reading {MessageId} from {EquipmentId} as invalid. Dropping it.",
            batch[0].Record.MessageId,
            batch[0].Record.EquipmentId
        );

        db.TelemetryRecords.Remove(batch[0].Record);
        await db.SaveChangesAsync(cancellationToken);
        metrics.Poisoned.Add(1);
        bufferDepth.Decrement(1);

        _consecutivePoisonDrops++;
        _isolating = false;
    }

    // Built before the stream opens so a bad record fails here, not mid-upload
    private static TelemetryRequest ToRequest(TelemetryRecord item) =>
        new()
        {
            MessageId = item.MessageId,
            EquipmentId = item.EquipmentId,
            SequenceNumber = item.SequenceNumber,
            OccurredAt = Timestamp.FromDateTimeOffset(item.OccurredAt),
            EngineTemperature = item.EngineTemperature,
            OilPressure = item.OilPressure,
        };

    // Distinct because a retried sensor request leaves rows sharing a traceparent
    // TryParse rather than trusting the column, since it came off disk
    // A malformed traceparent should cost one link, not the whole upload
    private static List<ActivityLink> BuildTraceLinks(List<PendingUpload> batch) =>
        batch
            .Select(p => p.Record.TraceParent)
            .Where(tp => !string.IsNullOrEmpty(tp))
            .Distinct()
            .Select(tp => ActivityContext.TryParse(tp, null, out var ctx) ? ctx : default)
            .Where(ctx => ctx != default)
            .Select(ctx => new ActivityLink(ctx))
            .ToList();

    private async Task RefreshGaugesAsync(EdgeDbContext db, CancellationToken cancellationToken)
    {
        // On a schedule rather than every pass, because COUNT(*) walks every row
        // Draining a full buffer is thousands of passes, and paying a scan of the remainder on each one is the edge device's CPU spent on a gauge
        _passesUntilDepthResync--;

        if (_passesUntilDepthResync <= 0)
        {
            bufferDepth.SetTo(await db.TelemetryRecords.CountAsync(cancellationToken));
            _passesUntilDepthResync = PassesBetweenDepthResyncs;
        }

        if (bufferDepth.Current == 0)
        {
            metrics.SetOldestAgeSeconds(0);
            return;
        }

        // A single row off the primary key, unlike the count above, so this one can run every pass
        // Nullable because the estimate can sit above the truth until the next resync, and a drained table would otherwise throw here
        var oldest = await db
            .TelemetryRecords.OrderBy(r => r.Id)
            .Select(r => (DateTimeOffset?)r.OccurredAt)
            .FirstOrDefaultAsync(cancellationToken);

        if (oldest is null)
        {
            metrics.SetOldestAgeSeconds(0);
            return;
        }

        // Measured from OccurredAt (the sensor's clock), not BufferedAt
        // That reflects true end-to-end staleness rather than gateway dwell time
        metrics.SetOldestAgeSeconds((DateTimeOffset.UtcNow - oldest.Value).TotalSeconds);
    }

    /// <summary>
    /// Exponential backoff with full jitter.
    /// </summary>
    /// <remarks>
    /// Jittered because every gateway in the fleet fails on the same cadence in an outage
    /// An unjittered wait reconnects them all at once and knocks the cloud back over
    ///
    /// Hand-rolled rather than Polly, which the emulator uses one hop down
    /// The wait is sized by loop state that outlives any one call, and it is entered from three different decisions
    /// That makes it this component's state machine, not a policy wrapped around a call
    /// </remarks>
    private async Task BackoffAsync(CancellationToken cancellationToken)
    {
        _consecutiveFailures++;

        var exponential = _baseBackoff * Math.Pow(2, Math.Min(_consecutiveFailures - 1, 10));
        var capped = exponential > _maxBackoff ? _maxBackoff : exponential;
        var jittered = TimeSpan.FromMilliseconds(
            Random.Shared.NextDouble() * capped.TotalMilliseconds
        );

        await SafeDelayAsync(jittered, cancellationToken);
    }

    // A classification rather than letting the exception reach the loop, because the four cases need four different decisions
    // One rethrow would flatten them back into "something failed", which is the bug this fixes
    private enum UploadOutcome
    {
        Answered,
        Unreachable,
        Malformed,
        Refused,
    }

    private readonly record struct UploadResult(UploadOutcome Outcome, int Accepted);

    // A record paired with the request built from it, rather than two lists walked by the same index
    // Deleting the first AcceptedCount rows is only correct while row i is the one that produced request i, so that correspondence is structural here instead of a convention
    private readonly record struct PendingUpload(TelemetryRecord Record, TelemetryRequest Request);

    // Task.Delay throws when the token trips, and this is called from catch blocks
    // Shutdown must not throw a second exception out of the handler
    private static async Task SafeDelayAsync(TimeSpan delay, CancellationToken cancellationToken)
    {
        try
        {
            await Task.Delay(delay, cancellationToken);
        }
        catch (OperationCanceledException) { }
    }
}
