name: Terraform Plan

on:
    pull_request:
        paths:
            - "infra/**"

jobs:
    plan:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: infra
        steps:
            - uses: actions/checkout@v4

            - uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.15.0

            - name: Terraform Init
              run: terraform init

            - name: Terraform Validate
              run: terraform validate

            - name: Plan dev
              run: terraform plan -var-file=dev.tfvars -input=false -no-color
              env:
                  TF_VAR_bootstrap_servers: ${{ secrets.DEV_KAFKA_BOOTSTRAP }}

            - name: Plan prod
              run: terraform plan -var-file=prod.tfvars -input=false -no-color
              env:
                  TF_VAR_bootstrap_servers: ${{ secrets.PROD_KAFKA_BOOTSTRAP }}
